//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanArabInternationalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SalesPromotionStatus
    {
        public string salesPromotionStatusId { get; set; }
        public string ledgerId { get; set; }
        public string salesPromotionDetails2Id { get; set; }
        public Nullable<decimal> qty { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> extraDate { get; set; }
        public string extra1 { get; set; }
        public string extra2 { get; set; }
    }
}
