//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanArabInternationalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_IntrestPayable
    {
        public string payableId { get; set; }
        public string voucherNo { get; set; }
        public string payableNo { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<bool> optional { get; set; }
        public string ledgerId { get; set; }
        public string paidTo { get; set; }
        public string narration { get; set; }
        public string branchId { get; set; }
        public string userId { get; set; }
        public string suffixPrefixId { get; set; }
        public Nullable<System.DateTime> extraDate { get; set; }
        public string extra1 { get; set; }
        public string extra2 { get; set; }
    }
}
