//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanArabInternationalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Branch
    {
        public string branchId { get; set; }
        public string currencyId { get; set; }
        public string branchName { get; set; }
        public string address { get; set; }
        public string phoneNo { get; set; }
        public string fax { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string web { get; set; }
        public string tinNo { get; set; }
        public string cstNo { get; set; }
        public string panNo { get; set; }
        public string startDate { get; set; }
        public Nullable<System.DateTime> extraDate { get; set; }
        public string extra1 { get; set; }
        public string extra2 { get; set; }
        public Nullable<bool> mainBranch { get; set; }
        public Nullable<System.DateTime> currentDate { get; set; }
        public byte[] logo { get; set; }
    }
}
