//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanArabInternationalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PriceList
    {
        public string priceListId { get; set; }
        public Nullable<System.DateTime> applicableFrom { get; set; }
        public string productCode { get; set; }
        public string pricingLevelId { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> rate { get; set; }
        public string unitId { get; set; }
        public string branchId { get; set; }
        public Nullable<System.DateTime> extraDate { get; set; }
        public string extra1 { get; set; }
        public string extra2 { get; set; }
    }
}
