//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanArabInternationalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DeleteStatus
    {
        public string SlNo { get; set; }
        public Nullable<bool> tbl_AccountLedger { get; set; }
        public Nullable<bool> tbl_Currency { get; set; }
        public Nullable<bool> tbl_LedgerPosting { get; set; }
        public Nullable<bool> tbl_Market { get; set; }
        public Nullable<bool> tbl_AccountGroup { get; set; }
        public Nullable<bool> tbl_CurrencyConversion { get; set; }
        public Nullable<bool> tbl_PurchaseOrderMaster { get; set; }
        public Nullable<bool> tbl_PurchaseOrderDetails1 { get; set; }
        public Nullable<bool> tbl_SalesOrderMaster { get; set; }
        public Nullable<bool> tbl_SalesOrderDetails1 { get; set; }
        public Nullable<bool> tbl_MaterialReceiptMaster { get; set; }
        public Nullable<bool> tbl_MaterialReceiptDetails1 { get; set; }
        public Nullable<bool> tbl_MaterialReceiptDetails2 { get; set; }
        public Nullable<bool> tbl_Batch { get; set; }
        public Nullable<bool> tbl_Employee { get; set; }
        public Nullable<bool> tbl_Reminder { get; set; }
        public Nullable<bool> tbl_SuffixPrefix { get; set; }
        public Nullable<bool> tbl_ContraMaster { get; set; }
        public Nullable<bool> tbl_ContraDetails { get; set; }
        public Nullable<bool> tbl_Holiday { get; set; }
        public bool tbl_PayHead { get; set; }
        public Nullable<bool> tbl_Designation { get; set; }
        public Nullable<bool> tbl_StandardRate { get; set; }
        public Nullable<bool> tbl_PriceList { get; set; }
        public Nullable<bool> tbl_TaxDetails { get; set; }
        public Nullable<bool> tbl_TaxMaster { get; set; }
        public Nullable<bool> tbl_Area { get; set; }
        public Nullable<bool> tbl_Brand { get; set; }
        public Nullable<bool> tbl_Godown { get; set; }
        public Nullable<bool> tbl_PricingLevel { get; set; }
        public Nullable<bool> tbl_ProductGroup { get; set; }
        public Nullable<bool> tbl_Unit { get; set; }
        public Nullable<bool> tbl_IntrestPayable { get; set; }
        public Nullable<bool> tbl_IntrestPayableDetails { get; set; }
        public Nullable<bool> tbl_IntrestReceivableDetails { get; set; }
        public Nullable<bool> tbl_IntrestReceivable { get; set; }
        public Nullable<bool> tbl_CompanyPath { get; set; }
        public Nullable<bool> tbl_PaymentDetails { get; set; }
        public Nullable<bool> tbl_Privilege { get; set; }
        public Nullable<bool> tbl_PrivilegeDetails { get; set; }
        public Nullable<bool> tbl_PartyBalance { get; set; }
        public Nullable<bool> tbl_IntrestParameterSettings { get; set; }
        public Nullable<bool> tbl_IntrestParameterDetails { get; set; }
        public Nullable<bool> tbl_PaymentMaster { get; set; }
        public Nullable<bool> tbl_BudgetMaster { get; set; }
        public Nullable<bool> tbl_BudgetPeriod { get; set; }
        public Nullable<bool> tbl_BudgetAllocation { get; set; }
        public Nullable<bool> tbl_BonusDeductionMaster { get; set; }
        public Nullable<bool> tbl_BonusDeductionDetails { get; set; }
        public Nullable<bool> tbl_AdvancePayment { get; set; }
        public Nullable<bool> tbl_AttendanceMaster { get; set; }
        public Nullable<bool> tbl_AttendanceDetails { get; set; }
        public Nullable<bool> tbl_DamageStockDetails2 { get; set; }
        public Nullable<bool> tbl_DamageStockDetails1 { get; set; }
        public Nullable<bool> tbl_DamagelStockMaster { get; set; }
        public Nullable<bool> tbl_StockPosting { get; set; }
        public Nullable<bool> tbl_PhysicalStockMaster { get; set; }
        public Nullable<bool> tbl_PhysicalStockDetails1 { get; set; }
        public Nullable<bool> tbl_PhysicalStockDetails2 { get; set; }
        public Nullable<bool> tbl_SalaryDetails2 { get; set; }
        public Nullable<bool> tbl_SalaryDetails1 { get; set; }
        public Nullable<bool> tbl_SalaryMaster { get; set; }
        public Nullable<bool> tbl_TransferMaster { get; set; }
        public Nullable<bool> tbl_TransferDetails { get; set; }
        public Nullable<bool> tbl_DeliveryNoteMaster { get; set; }
        public Nullable<bool> tbl_DeliveryNoteDetails1 { get; set; }
        public Nullable<bool> tbl_DeliveryNoteDetails2 { get; set; }
        public Nullable<bool> tbl_ReceiptDetails { get; set; }
        public Nullable<bool> tbl_ReceiptMaster { get; set; }
        public Nullable<bool> tbl_AdditionalCost { get; set; }
        public Nullable<bool> tbl_RejectionInMaster { get; set; }
        public Nullable<bool> tbl_RejectionInDetails1 { get; set; }
        public Nullable<bool> tbl_RejectionInDetails2 { get; set; }
        public Nullable<bool> tbl_PDCPayable { get; set; }
        public Nullable<bool> tbl_RejectionOutDetails1 { get; set; }
        public Nullable<bool> tbl_RejectionOutDetails2 { get; set; }
        public Nullable<bool> tbl_RejectionOutMaster { get; set; }
        public Nullable<bool> tbl_PDCReceivable { get; set; }
        public Nullable<bool> tbl_ManufacturingJournalMaster { get; set; }
        public Nullable<bool> tbl_ManufacturingJournalDetails { get; set; }
        public Nullable<bool> tbl_PurchaseMaster { get; set; }
        public Nullable<bool> tbl_PurchaseDetails2 { get; set; }
        public Nullable<bool> tbl_PurchaseDetails1 { get; set; }
        public Nullable<bool> tbl_ManufacturingJounralDetails2 { get; set; }
        public Nullable<bool> tbl_JournelDetails { get; set; }
        public Nullable<bool> tbl_JournelMaster { get; set; }
        public Nullable<bool> tbl_VatJournalMaster { get; set; }
        public Nullable<bool> tbl_VatJournalDetails { get; set; }
        public Nullable<bool> tbl_PurchaseReturnMaster { get; set; }
        public Nullable<bool> tbl_PurchaseReturnDetails2 { get; set; }
        public Nullable<bool> tbl_PurchaseReturnDetails1 { get; set; }
        public Nullable<bool> tbl_SalesDetails2 { get; set; }
        public Nullable<bool> tbl_SalesDetails1 { get; set; }
        public Nullable<bool> tbl_SalesMaster { get; set; }
        public Nullable<bool> tbl_SalesReturnMaster { get; set; }
        public Nullable<bool> tbl_SalesReturnDetails1 { get; set; }
        public Nullable<bool> tbl_SalesReturnDetails2 { get; set; }
        public Nullable<bool> tbl_CounterSaleDetails1 { get; set; }
        public Nullable<bool> tbl_CounterSaleMaster { get; set; }
        public Nullable<bool> tbl_PackageSale { get; set; }
        public Nullable<bool> tbl_ComponentsSettings { get; set; }
        public Nullable<bool> tbl_BOM { get; set; }
        public Nullable<bool> tbl_ProductDetails { get; set; }
        public Nullable<bool> tbl_UnitConversion { get; set; }
        public Nullable<bool> tbl_Product { get; set; }
        public Nullable<bool> tbl_InvoiceDeclaration { get; set; }
        public Nullable<bool> tbl_SalarySettings { get; set; }
        public Nullable<bool> tbl_SalarySettingsDetails { get; set; }
        public Nullable<bool> tbl_QuotationMaster { get; set; }
        public Nullable<bool> tbl_QuotationDetails { get; set; }
        public Nullable<bool> tbl_Quotation { get; set; }
        public Nullable<bool> tbl_GiftItems { get; set; }
        public Nullable<bool> tbl_SalesPromotionMaster { get; set; }
        public Nullable<bool> tbl_SalesPromotionDetails1 { get; set; }
        public Nullable<bool> tbl_SalesPromotionDetails2 { get; set; }
        public Nullable<bool> tbl_SalesPromotionStatus { get; set; }
        public Nullable<bool> tbl_GatePass { get; set; }
        public Nullable<bool> tbl_Rack { get; set; }
        public Nullable<bool> tbl_VehicleType { get; set; }
        public Nullable<bool> tbl_Route { get; set; }
        public Nullable<bool> tbl_Counter { get; set; }
        public Nullable<bool> tbl_ServiceMaster { get; set; }
        public Nullable<bool> tbl_ServiceDetails { get; set; }
        public Nullable<bool> tbl_UsedStockDetails2 { get; set; }
        public Nullable<bool> tbl_UsedStockDetails1 { get; set; }
        public Nullable<bool> tbl_UsedStockMaster { get; set; }
        public Nullable<bool> tbl_Service { get; set; }
    }
}
