//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanArabInternationalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PartyBalance
    {
        public string balanceId { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string ledgerId { get; set; }
        public string voucherType { get; set; }
        public string voucherNo { get; set; }
        public string againstVoucherType { get; set; }
        public string againstvoucherNo { get; set; }
        public string referenceType { get; set; }
        public Nullable<decimal> debit { get; set; }
        public Nullable<decimal> credit { get; set; }
        public Nullable<bool> optional { get; set; }
        public Nullable<int> creditPeriod { get; set; }
        public string branchId { get; set; }
        public Nullable<System.DateTime> extraDate { get; set; }
        public string extra1 { get; set; }
        public string extra2 { get; set; }
        public string currecyConversionId { get; set; }
    }
}
