//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanArabInternationalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SalesDetails1
    {
        public string salesDetails1Id { get; set; }
        public string salesMasterId { get; set; }
        public string deliveryNoteDetails1Id { get; set; }
        public string orderDetails1Id { get; set; }
        public string productCode { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> freeQty { get; set; }
        public Nullable<decimal> rate { get; set; }
        public string unitId { get; set; }
        public Nullable<decimal> discountPercentage { get; set; }
        public string taxId { get; set; }
        public string taxType { get; set; }
        public Nullable<decimal> taxAmount { get; set; }
        public Nullable<decimal> grossAmount { get; set; }
        public Nullable<decimal> netAmount { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string packageSaleId { get; set; }
        public Nullable<System.DateTime> extraDate { get; set; }
        public string extra1 { get; set; }
        public string extra2 { get; set; }
        public string quotationDetailsId { get; set; }
        public Nullable<int> SlNo { get; set; }
        public Nullable<decimal> newQty { get; set; }
        public string newProductName { get; set; }
    }
}
