//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanArabInternationalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employee
    {
        public string employeeId { get; set; }
        public string employeeName { get; set; }
        public string designationId { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string meritalStatus { get; set; }
        public string gender { get; set; }
        public string qualification { get; set; }
        public string address { get; set; }
        public string phoneNo { get; set; }
        public string mobileNo { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> joiningDate { get; set; }
        public Nullable<System.DateTime> terminationDate { get; set; }
        public Nullable<bool> active { get; set; }
        public string narration { get; set; }
        public string bloodGroup { get; set; }
        public string branchId { get; set; }
        public Nullable<System.DateTime> extraDate { get; set; }
        public string extra1 { get; set; }
        public string extra2 { get; set; }
        public string employeeCode { get; set; }
        public string routeId { get; set; }
        public string areaId { get; set; }
        public string marketId { get; set; }
        public string passportNo { get; set; }
        public Nullable<System.DateTime> passportExpDate { get; set; }
        public string labourCardNo { get; set; }
        public Nullable<System.DateTime> labourCardExpDate { get; set; }
        public string visaNo { get; set; }
        public Nullable<System.DateTime> visaExpDate { get; set; }
    }
}
