//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanArabInternationalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Medical
    {
        public int Id { get; set; }
        public string FormSl { get; set; }
        public Nullable<System.DateTime> MedicalDate { get; set; }
        public string MedicalReport { get; set; }
        public Nullable<System.DateTime> MedicalExpDate { get; set; }
        public string ReportDescription { get; set; }
        public string UserId { get; set; }
        public Nullable<int> MedicalContactAmount { get; set; }
        public string voucherNo { get; set; }
    }
}
