//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanArabInternationalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Passport
    {
        public int Id { get; set; }
        public string PslNo { get; set; }
        public string PassportNo { get; set; }
        public string PassportMakeBy { get; set; }
        public Nullable<System.DateTime> PassportSubmitDate { get; set; }
        public Nullable<System.DateTime> PassportDeleveryDate { get; set; }
        public string UserId { get; set; }
        public string Remarks { get; set; }
        public string PSlipNo { get; set; }
        public Nullable<System.DateTime> PassportExpireDate { get; set; }
    }
}
