//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanArabInternationalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Product
    {
        public string productCode { get; set; }
        public string productName { get; set; }
        public string groupId { get; set; }
        public string brandId { get; set; }
        public string unitId { get; set; }
        public Nullable<bool> allowBatch { get; set; }
        public Nullable<bool> multipleUnit { get; set; }
        public string branchId { get; set; }
        public Nullable<System.DateTime> extraDate { get; set; }
        public string extra1 { get; set; }
        public string extra2 { get; set; }
        public string partNo { get; set; }
        public string productImage { get; set; }
    }
}
