//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanArabInternationalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ServiceDetails
    {
        public string ServiceDetailsId { get; set; }
        public string ServiceMasterId { get; set; }
        public Nullable<int> SlNo { get; set; }
        public string serviceId { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<System.DateTime> extraDate { get; set; }
        public string extra1 { get; set; }
        public string extra2 { get; set; }
    }
}
