//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanArabInternationalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AccountLedgerToCopy
    {
        public string ledgerId { get; set; }
        public string ledgerName { get; set; }
        public string groupId { get; set; }
        public Nullable<bool> affectInventory { get; set; }
        public Nullable<decimal> openingBalance { get; set; }
        public string crOrDr { get; set; }
        public string narration { get; set; }
        public string name { get; set; }
        public string accountNo { get; set; }
        public string address { get; set; }
        public string phoneNo { get; set; }
        public string faxNo { get; set; }
        public string email { get; set; }
        public Nullable<int> creditPeriod { get; set; }
        public Nullable<decimal> creditLimit { get; set; }
        public string pricingLevelId { get; set; }
        public string currencyId { get; set; }
        public Nullable<bool> interestOrNot { get; set; }
        public string branchId { get; set; }
        public string marketId { get; set; }
        public Nullable<bool> defaultt { get; set; }
        public string tinNumber { get; set; }
        public string cstNumber { get; set; }
        public string panNumber { get; set; }
        public Nullable<System.DateTime> extraDate { get; set; }
        public string extra1 { get; set; }
        public string extra2 { get; set; }
    }
}
