//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanArabInternationalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SalesDetails2
    {
        public string salesDetails2Id { get; set; }
        public string salesDetails1Id { get; set; }
        public string deliveryNoteDetails2Id { get; set; }
        public string batchId { get; set; }
        public string godownId { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> freeQty { get; set; }
        public Nullable<decimal> rate { get; set; }
        public string unitId { get; set; }
        public Nullable<decimal> discountPercentage { get; set; }
        public Nullable<decimal> netAmount { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<System.DateTime> extraDate { get; set; }
        public string extra1 { get; set; }
        public string extra2 { get; set; }
        public string rackId { get; set; }
    }
}
