//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanArabInternationalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Settings
    {
        public string settingsId { get; set; }
        public string branchId { get; set; }
        public Nullable<bool> budget { get; set; }
        public Nullable<bool> payRoll { get; set; }
        public Nullable<bool> tax { get; set; }
        public Nullable<bool> multiCurrency { get; set; }
        public Nullable<bool> billByBill { get; set; }
        public Nullable<bool> interestCalculation { get; set; }
        public Nullable<bool> discount { get; set; }
        public Nullable<bool> freeQuantity { get; set; }
        public Nullable<bool> automaticProductCodeGeneration { get; set; }
        public Nullable<bool> barcodeGeneration { get; set; }
        public Nullable<bool> maintainBatch { get; set; }
        public string expiryReminder { get; set; }
        public Nullable<bool> maintainGodown { get; set; }
        public Nullable<bool> suffixPrefix { get; set; }
        public Nullable<bool> lowStockReminderPopUp { get; set; }
        public Nullable<bool> messageBox { get; set; }
        public string printer { get; set; }
        public string stockCalculatingMethod { get; set; }
        public string negativeStockStatus { get; set; }
        public Nullable<int> purchaseReturnLimit { get; set; }
        public Nullable<int> salesReturnLimit { get; set; }
        public Nullable<bool> directPrint { get; set; }
        public Nullable<System.DateTime> extraDate { get; set; }
        public string extra1 { get; set; }
        public string extra2 { get; set; }
        public Nullable<bool> currencySuffix { get; set; }
        public string negativeCashTransaction { get; set; }
        public Nullable<bool> allowRack { get; set; }
        public Nullable<bool> messageBoxAddEdit { get; set; }
        public Nullable<bool> messageBoxDelete { get; set; }
        public Nullable<bool> messageBoxClose { get; set; }
        public Nullable<bool> messageBoxRowRemove { get; set; }
        public string formType { get; set; }
        public string taxType { get; set; }
        public Nullable<bool> showPurchaseRate { get; set; }
        public Nullable<bool> showMRP { get; set; }
        public Nullable<bool> showUnit { get; set; }
        public Nullable<bool> showDiscountAmount { get; set; }
        public Nullable<bool> tickPrintAfterSave { get; set; }
        public Nullable<bool> showProductCode { get; set; }
        public Nullable<bool> showCompanyForEstimatePrint { get; set; }
        public Nullable<int> paperOut { get; set; }
        public Nullable<bool> showBrand { get; set; }
        public Nullable<bool> showSalesmanInPrint { get; set; }
        public Nullable<bool> vehicle { get; set; }
        public Nullable<bool> vatIncluded { get; set; }
        public Nullable<bool> vatCessIncluded { get; set; }
        public Nullable<bool> billDiscountPer { get; set; }
    }
}
