//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanArabInternationalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ServiceMaster
    {
        public string ServiceMasterId { get; set; }
        public string voucherNo { get; set; }
        public string invoiceNo { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> creditPeriod { get; set; }
        public string ledgerId { get; set; }
        public string pricingLevelId { get; set; }
        public string employeeId { get; set; }
        public string salesAccount { get; set; }
        public Nullable<bool> optional { get; set; }
        public string narration { get; set; }
        public string customerName { get; set; }
        public string currecyConversionId { get; set; }
        public string taxType { get; set; }
        public string taxId { get; set; }
        public Nullable<decimal> taxAmount { get; set; }
        public Nullable<decimal> totalTax { get; set; }
        public Nullable<decimal> additionalCost { get; set; }
        public Nullable<decimal> billDiscount { get; set; }
        public Nullable<decimal> totalAmount { get; set; }
        public string userId { get; set; }
        public string branchId { get; set; }
        public string suffixPrefixId { get; set; }
        public string lrNo { get; set; }
        public string transportCompany { get; set; }
        public Nullable<bool> packageSale { get; set; }
        public Nullable<System.DateTime> extraDate { get; set; }
        public string extra1 { get; set; }
        public string extra2 { get; set; }
        public string quotationMasterId { get; set; }
        public string skckNo { get; set; }
        public string vehicleTypeId { get; set; }
        public string vehicleNo { get; set; }
    }
}
