//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanArabInternationalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProductDetails
    {
        public string productDetailsId { get; set; }
        public string productCode { get; set; }
        public string branchId { get; set; }
        public Nullable<decimal> purchaseRate { get; set; }
        public Nullable<decimal> salesRate { get; set; }
        public Nullable<decimal> mrp { get; set; }
        public string taxId { get; set; }
        public Nullable<decimal> minimumStock { get; set; }
        public Nullable<decimal> maximunStock { get; set; }
        public Nullable<decimal> reorderLevel { get; set; }
        public Nullable<decimal> openingStock { get; set; }
        public string taxType { get; set; }
        public string narration { get; set; }
        public Nullable<bool> allowBatch { get; set; }
        public Nullable<bool> bom { get; set; }
        public Nullable<bool> allowComponentSale { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> showReminder { get; set; }
        public Nullable<System.DateTime> extraDate { get; set; }
        public string extra1 { get; set; }
        public string extra2 { get; set; }
        public Nullable<bool> gatePass { get; set; }
        public Nullable<decimal> fixedSalesRate { get; set; }
        public Nullable<decimal> avgCost { get; set; }
        public Nullable<decimal> fifoValue { get; set; }
        public Nullable<decimal> avgRate { get; set; }
        public Nullable<decimal> fifoRate { get; set; }
    }
}
