//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanArabInternationalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SuffixPrefix
    {
        public string suffixPrefixId { get; set; }
        public string branchId { get; set; }
        public string suffix { get; set; }
        public string prefix { get; set; }
        public Nullable<int> startIndex { get; set; }
        public string voucherType { get; set; }
        public Nullable<System.DateTime> extraDate { get; set; }
        public string extra1 { get; set; }
        public string extra2 { get; set; }
        public string yearId { get; set; }
    }
}
