//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanArabInternationalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SalarySettingsDetails
    {
        public string salarySettingsDetailsId { get; set; }
        public string salarySettingsId { get; set; }
        public string payheadId { get; set; }
        public string rsOrPer { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string payheadIdOf { get; set; }
        public Nullable<System.DateTime> extraDate { get; set; }
        public string extra1 { get; set; }
        public string extra2 { get; set; }
    }
}
