//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanArabInternationalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VisaProcessing
    {
        public int Id { get; set; }
        public string FormSl { get; set; }
        public string Cateogry { get; set; }
        public Nullable<bool> Okela { get; set; }
        public string VisaNo { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string IssuePlace { get; set; }
        public Nullable<System.DateTime> VisaStapmingDate { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> MusaniDate { get; set; }
        public string MusaniRemarks { get; set; }
        public Nullable<int> ContractAmount { get; set; }
        public string DrivingLicnc { get; set; }
        public Nullable<System.DateTime> OkeylaDate { get; set; }
        public string OkeylaNo { get; set; }
        public string OkeylaRemarks { get; set; }
        public string SponserId { get; set; }
        public string SponcerName { get; set; }
        public string VisaReffNo { get; set; }
        public string voucherno { get; set; }
    }
}
