//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanArabInternationalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SalesPromotionDetails2
    {
        public string salesPromotionDetails2Id { get; set; }
        public string salesPromotionDetails1Id { get; set; }
        public Nullable<decimal> fromQty { get; set; }
        public Nullable<decimal> toQty { get; set; }
        public string unitId { get; set; }
        public string giftType { get; set; }
        public string giftItem { get; set; }
        public Nullable<decimal> giftQty { get; set; }
        public string giftUnitId { get; set; }
        public Nullable<System.DateTime> extraDate { get; set; }
        public string extra1 { get; set; }
        public string extra2 { get; set; }
    }
}
