//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanArabInternationalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Temps
    {
        public int Id { get; set; }
        public string SL { get; set; }
        public string voucherType { get; set; }
        public string voucherNo { get; set; }
        public string Date { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public string MasterId { get; set; }
        public string Priority { get; set; }
        public string PID { get; set; }
        public string LID { get; set; }
        public string ledgerName { get; set; }
    }
}
