//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanArabInternationalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Job
    {
        public decimal jobId { get; set; }
        public string jobTypeId { get; set; }
        public string clientId { get; set; }
        public string unitId { get; set; }
        public string flightId { get; set; }
        public string branchId { get; set; }
        public string salesmanId { get; set; }
        public string consignee { get; set; }
        public string jobCode { get; set; }
        public string awbOrBl { get; set; }
        public string hawbOrHbl { get; set; }
        public string noOfPieces { get; set; }
        public string notify { get; set; }
        public string grossWeight { get; set; }
        public string actualWeight { get; set; }
        public string commodity { get; set; }
        public string volume { get; set; }
        public string origin { get; set; }
        public string exitPoint { get; set; }
        public Nullable<System.DateTime> dateOfDeparture { get; set; }
        public Nullable<System.DateTime> dateOfArrival { get; set; }
        public Nullable<System.DateTime> timeOfDeparture { get; set; }
        public Nullable<System.DateTime> timeOfArrival { get; set; }
        public string suffixPrefixId { get; set; }
        public string shipperId { get; set; }
        public string destination { get; set; }
        public string AirlineNo { get; set; }
        public string userId { get; set; }
        public string jobInvoiceNo { get; set; }
        public Nullable<System.DateTime> invoiceDate { get; set; }
        public Nullable<decimal> totalAmount { get; set; }
        public Nullable<bool> optional { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> extraDate { get; set; }
        public string extra1 { get; set; }
        public string extra2 { get; set; }
        public string voucherNo { get; set; }
        public string currecyConversionId { get; set; }
    }
}
