//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanArabInternationalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FlyDetails
    {
        public int Id { get; set; }
        public string UserID { get; set; }
        public string FormSlNo { get; set; }
        public Nullable<System.DateTime> FlyDate { get; set; }
        public string FlyDestination { get; set; }
        public string TraAgName { get; set; }
        public string Status { get; set; }
        public string FlighNo { get; set; }
        public Nullable<System.DateTime> FileDeleveryDate { get; set; }
    }
}
